### ISSUE TITLE
bug: stacktrace on siginit signal

### ISSUE THREAD

**Issue by hegerdes** [alex1989hu/kubelet-serving-cert-approver#239]
I use this app to run it as a k8s job on new clusters. The job creates a pod and allows it run run x minutes and then exits.

I've noticed that when the job is to be terminated it prints the following log and stacktrace. I think the exit process is not properly handled here. I have not tested it with all exit signals but with `SIGINIT` which is the initial and most common signal to use. In my case the process still exited with status code 0. 

Do you know why this is printed?
```
csr-approver {"level":"info","time":"2024-10-13T15:06:02.917Z","caller":"cmd/serve.go:66","msg":"Kubelet Serving Certificate Approver has been started","GitBranch":"main","GitCommit":"debdbf39","Time":"Fri Oct 11 17:38:34 UTC 2024","namespace":"kubelet-serving-cert-approver","ha":false,"debug":false}
csr-approver {"level":"info","time":"2024-10-13T15:06:02.918Z","caller":"cmd/serve.go:77","msg":"Try to talk to Kubernetes API Server, will exit in case of failure"}
csr-approver {"level":"info","time":"2024-10-13T15:06:02.941Z","caller":"cmd/serve.go:110","msg":"Successfully connected to Kubernetes API Server"}
csr-approver [controller-runtime] log.SetLogger(...) was never called; logs will not be displayed.
csr-approver Detected at:
csr-approver     >  goroutine 61 [running]:
csr-approver     >  runtime/debug.Stack()
csr-approver     >      runtime/debug/stack.go:26 +0x5e
csr-approver     >  sigs.k8s.io/controller-runtime/pkg/log.eventuallyFulfillRoot()
csr-approver     >      sigs.k8s.io/controller-runtime@v0.19.0/pkg/log/log.go:60 +0xcd
csr-approver     >  sigs.k8s.io/controller-runtime/pkg/log.(*delegatingLogSink).Enabled(0xc000524000, 0x0)
csr-approver     >      sigs.k8s.io/controller-runtime@v0.19.0/pkg/log/deleg.go:111 +0x32
csr-approver     >  github.com/go-logr/logr.Logger.Info({{0x2195c68?, 0xc000524000?}, 0x2191948?}, {0x1f0a638, 0x35}, {0x0, 0x0, 0x0})
csr-approver     >      github.com/go-logr/logr@v1.4.2/logr.go:276 +0x6e
csr-approver     >  sigs.k8s.io/controller-runtime/pkg/metrics/server.(*defaultServer).Start.func1()
csr-approver     >      sigs.k8s.io/controller-runtime@v0.19.0/pkg/metrics/server/server.go:254 +0x74
csr-approver     >  created by sigs.k8s.io/controller-runtime/pkg/metrics/server.(*defaultServer).Start in goroutine 59
csr-approver     >      sigs.k8s.io/controller-runtime@v0.19.0/pkg/metrics/server/server.go:252 +0x81b
Stream closed EOF for kubelet-serving-cert-approver/csr-approve-job-v6qf5 (shell)
Stream closed EOF for kubelet-serving-cert-approver/csr-approve-job-v6qf5 (csr-approver)

```

**Comment by alex1989hu** [comment]
Dear @hegerdes,

Thank you for your feedback. I can verify that the issue reported is valid. b3d06f859141f127ea965eb12d7e51de0d68bc35 addresses the bug you reported. I published a new version [v0.8.7](https://github.com/alex1989hu/kubelet-serving-cert-approver/releases/tag/v0.8.7) which contains the commit mentioned above.

Best regards,
Alex
